import "./globals.css";
import localFont from "next/font/local";

const shams = localFont({
  src: [
    {
      path: "../../public/fonts/Shams-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Shams-SemiBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Shams-Bold.otf",
      weight: "900",
      style: "normal",
    },
  ],

  variable: "--font-shams",
  display: "swap",
  fallback: ["Arial", "sans-serif"],
});

const eloquia = localFont({
  src: [
    {
      path: "../../public/fonts/EloquiaDisplay-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/EloquiaDisplay-SemiBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/EloquiaDisplay-Bold.otf",
      weight: "900",
      style: "normal",
    },
  ],

  variable: "--font-eloquia",
  display: "swap",
  fallback: ["Arial", "sans-serif"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${shams.variable} ${eloquia.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
